language: java

jdk:
  - openjdk8

jobs:
  include:
    - stage: "Build Core"
      script:
        - cd core
        - mvn clean verify
    - stage: "Build Plugins"
      script:
        - cd spigot
        - mvn clean verify
    - stage: "Build Plugins"
      script:
        - cd bungeecord
        - mvn clean verify

cache:
  directories:
    - $HOME/.m2